FROM steamcmd/steamcmd:ubuntu-24

ENV AUTOSAVENUM="5" \
    DEBUG="false" \
    DISABLESEASONALEVENTS="false" \
    GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved" \
    GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames" \
    LOG="false" \
    LOGNETLEVEL="Error" \
    LOGNETTRAFFICLEVEL="Warning" \
    MAXOBJECTS="2162688" \
    MAXPLAYERS="4" \
    MAXTICKRATE="30" \
    PGID="1014" \
    PUID="1014" \
    ROOTLESS="true" \
    SERVERGAMEPORT="7777" \
    SERVERSTREAMING="true" \
    SKIPUPDATE="false" \
    STEAMAPPID="1690800" \
    STEAMBETA="false" \
    TIMEOUT="30" \
    VMOVERRIDE="false"

RUN set -x \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y gosu xdg-user-dirs curl jq tzdata --no-install-recommends \
 && rm -rf /var/lib/apt/lists/* \
 && userdel ubuntu \
 && groupadd -r steam -g $PGID \
 && useradd -ms /bin/bash --no-log-init -r -u $PUID -g $PGID steam \
 && gosu nobody true \
 && mkdir -p /home/steam/.steam/root \
 /home/steam/.steam/steam 

RUN mkdir -p /config \
 && chown steam:steam /config

COPY init.sh healthcheck.sh /
COPY --chown=steam:steam run.sh /home/steam/

WORKDIR /config

ARG VERSION="DEV"
ENV VERSION=$VERSION
LABEL version=$VERSION


STOPSIGNAL SIGINT

EXPOSE 7777/udp 7777/tcp

USER steam
ENTRYPOINT [ "/init.sh" ]
